[pytest]
addopts = --cov=app.core.auth --cov=app.api.routes.health_route --cov=app.api.routes.lobby_route --cov=app.api.routes.matches_route --cov-report=term-missing --cov-report=xml
testpaths = tests
pythonpath = .
